fake_global_chat_messages = [
    { 'name': 'user3', 'message': 'hello this is user3' },
    { 'name': 'user4', 'message': 'hello this is user4' },
    { 'name': 'user5', 'message': 'hello this is user5' },
    { 'name': 'user6', 'message': 'hello this is user6' },
    { 'name': 'user7', 'message': 'hello this is user7' },
    { 'name': 'user8', 'message': 'hello this is user8' },
    { 'name': 'user9', 'message': 'hello this is user9' },
    { 'name': 'user10', 'message': 'hello this is user10' },
    { 'name': 'user11', 'message': 'hello this is user11' },
    { 'name': 'user12', 'message': 'hello this is user12' },
    { 'name': 'user13', 'message': 'hello this is user13' },
    { 'name': 'user14', 'message': 'hello this is user14' },
    { 'name': 'user3', 'message': 'hello this is user3' },
    { 'name': 'user4', 'message': 'hello this is user4' },
    { 'name': 'user5', 'message': 'hello this is user5' },
    { 'name': 'user6', 'message': 'hello this is user6' },
    { 'name': 'user7', 'message': 'hello this is user7' },
    { 'name': 'user8', 'message': 'hello this is user8' },
    { 'name': 'user9', 'message': 'hello this is user9' },
    { 'name': 'user10', 'message': 'hello this is user10' },
    { 'name': 'user11', 'message': 'hello this is user11' },
    { 'name': 'user12', 'message': 'hello this is user12' },
    { 'name': 'user13', 'message': 'hello this is user13' },
    { 'name': 'user14', 'message': 'hello this is user14' }
]