version: '3.8'

services:
  django-frontend:
    container_name: django-frontend
    build:
      context: ./django-frontend
    volumes:
      - ./django-frontend:/app
    command: python app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - transcendence-network

networks:
  transcendence-network:
    driver: bridge
