# Generated by Django 5.0.4 on 2024-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('id_42', models.CharField(blank=True, max_length=42)),
                ('friends', models.ManyToManyField(blank=True, to='users.user')),
            ],
        ),
    ]
