# Generated by Django 5.0.3 on 2024-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
