# Generated by Django 5.0.3 on 2024-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManager', '0002_alter_game_player1_id_alter_game_player2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
