# Generated by Django 5.0.3 on 2024-08-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManager', '0004_game_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
