# Generated by Django 5.0.3 on 2024-09-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManager', '0005_game_loser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
    ]
