#!/bin/sh
set -e

# Wait for PostgreSQL to be ready
until pg_isready ; do
  echo "Waiting for PostgreSQL to be ready..."
  sleep 2
done

# Connect to PostgreSQL as root
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
  -- Create users and assign privileges
  CREATE USER $FRONTEND_DB_USER WITH PASSWORD '$FRONTEND_DB_PASSWORD';
  CREATE USER $API_GATEWAY_DB_USER WITH PASSWORD '$API_GATEWAY_DB_PASSWORD';
  CREATE USER $API_AUTHENTICATION_DB_USER WITH PASSWORD '$API_AUTHENTICATION_DB_PASSWORD';
  CREATE USER $API_USERS_DB_USER WITH PASSWORD '$API_USERS_DB_PASSWORD';
  CREATE USER $API_GAME_DB_USER WITH PASSWORD '$API_GAME_DB_PASSWORD';

  -- Create databases
  CREATE DATABASE $FRONTEND_DB_NAME;
  CREATE DATABASE $API_GATEWAY_DB_NAME;
  CREATE DATABASE $API_AUTHENTICATION_DB_NAME;
  CREATE DATABASE $API_USERS_DB_NAME;
  CREATE DATABASE $API_GAME_DB_NAME;

  -- Grant privileges on databases
  GRANT ALL PRIVILEGES ON DATABASE $FRONTEND_DB_NAME TO $FRONTEND_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $API_GATEWAY_DB_NAME TO $API_GATEWAY_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $API_AUTHENTICATION_DB_NAME TO $API_AUTHENTICATION_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $API_USERS_DB_NAME TO $API_USERS_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $API_GAME_DB_NAME TO $API_GAME_DB_USER;

EOSQL

# Grant privileges on public schema within each database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$FRONTEND_DB_NAME" <<-EOSQL
  GRANT ALL PRIVILEGES ON SCHEMA public TO $FRONTEND_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_GATEWAY_DB_NAME" <<-EOSQL
  GRANT ALL PRIVILEGES ON SCHEMA public TO $API_GATEWAY_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_AUTHENTICATION_DB_NAME" <<-EOSQL
  GRANT ALL PRIVILEGES ON SCHEMA public TO $API_AUTHENTICATION_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_USERS_DB_NAME" <<-EOSQL
  GRANT ALL PRIVILEGES ON SCHEMA public TO $API_USERS_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_GAME_DB_NAME" <<-EOSQL
  GRANT ALL PRIVILEGES ON SCHEMA public TO $API_GAME_DB_USER;
EOSQL